### PR TITLE
Prevent structlogger from prepending timestamp by default

### PR DESCRIPTION
**Pull request by alphachai**
```
>>> from lpipe.logging import LPLogger
>>> l = LPLogger()
>>> l.info("asdf")
{"event": "asdf", "level": 20, "timestamp": "2020-07-30T20:23:22.671150Z"}
```

### CODE REVIEW

**Comment by xiang-zhu** [comment]
It's a change of system outputs/side effects, I'm not sure there's a good reason for not have test cover it.

**Comment by alphachai** [comment]
*technically*, yes. In reality, this is the only change.

```
structlog.configure(
            processors=[
                structlog.processors.StackInfoRenderer(),
                structlog.dev.set_exc_info,
                structlog.processors.format_exc_info,
                structlog.processors.TimeStamper(),
                structlog.dev.ConsoleRenderer(),
            ]
        )
```
becomes
```
structlog.configure(
            processors=[
                structlog.processors.StackInfoRenderer(),
                structlog.dev.set_exc_info,
                structlog.processors.format_exc_info,
                structlog.dev.ConsoleRenderer(),
            ]
        )
```

This is taken from the structlog documentation.

I'd prefer to avoid testing stdout of structlog, since it has it's own tests.

**Comment by xiang-zhu** [comment]
You could have a test using mock to test the list of processors, without have to test output from third party library

**Comment by alphachai** [comment]
The list of processors on LPLogger have not changed. Only the configuration of structlog.

```
>>> l = LPLogger()
>>> l._logger._processors
[<structlog.processors.TimeStamper object at 0x103f5b0d8>, <structlog.processors.JSONRenderer object at 0x10304b668>]
```

Like I said, I'd prefer not to test deeper into structlog. Doing so would be equivalent to checking values inside the sentry-sdk based on the inputs we provide it when initializing. The library could change what sits under the hood at any time. I don't want to write tests that check a third party library does what it says it does unless absolutely necessary.

**Comment by xiang-zhu** [comment]
Wasn't `processors` argument in the call of `structlog.configure`  the one changed? I think there's a difference between "check thrid party library behavior" vs "check how the third party library is used".

**Comment by alphachai** [comment]
The processors set in structlog's config are somehow different from the ones used to wrap the logger, and while this MR is showing the *addition* of new lines, it's actually a *subtraction* of one line, the default TimeStamper processor. This setup was pulled directly from the structlog examples. I'd welcome an MR to add more tests, but I'm not interested in writing them, as they provide me no additional confidence.

**Pull request merged**
